### PR TITLE
chore: Add issue and pull request templates

### PR DESCRIPTION
**Pull request by BurningEnlightenment**

### CODE REVIEW

**Review by Holzhaus — DISMISSED** [review]

**Comment by Holzhaus** [comment]
You didn't open an issue for this PR \*scnr\* :)

**Comment by Holzhaus** [comment]
FYI you can install the [`pre-commit`](https://pre-commit.com/) tool and then run `pre-commit install` inside the git repo to ensure that the changes you are about to commit pass the linters locally before pushing them.

**Comment by BurningEnlightenment** [comment]
@Holzhaus do you mind if I exclude the templates from the markdown checks?

I'd also add a short contributing.md and the [Contributor Covenant] as a Code of Conduct to fulfill the [GitHub Community Standards].

[Contributor Covenant]: https://www.contributor-covenant.org/
[GitHub Community Standards]: https://github.com/sphinx-contrib/multiversion/community

**Comment by Holzhaus** [comment]
> @Holzhaus do you mind if I exclude the templates from the markdown checks?

Depends. In general we should only exclude files if we have a good reason. Could you elaborate why you think this is necessary in this case?

> I'd also add a short contributing.md and the [Contributor Covenant](https://www.contributor-covenant.org/) as a Code of Conduct to fulfill the [GitHub Community Standards](https://github.com/sphinx-contrib/multiversion/community).

Ok, thanks.

**Comment by BurningEnlightenment** [comment]
> Depends. In general we should only exclude files if we have a good reason. Could you elaborate why you think this is necessary in this case?

The rule violations boil down to:

- MD002 First header should be a top level header: This makes no sense / looks very awkward in issue or PR descriptions.
- MD022 Headers should be surrounded by blank lines: It feels overly verbose to separate the comments from the headers given that there is no actual content here. Also remember this has to fit into the GitHub comment box, i.e. vertical space shouldn't be wasted if possible.
- MD026 Trailing punctuation in header: I can remove the colons from the issue template headers, but I think they make sense in this case
- MD012 Multiple consecutive blank lines: I left the newlines, because the user would have to always add them anyways.

Alternatively we could create a custom ruleset for these files, but I think that would be overkill for something that will likely never change again…

**Review by Holzhaus — CHANGES_REQUESTED** [review]
Let's fix MD026 (see above).

The reasoning regarding MD002, MD022 and MD012 make sense to me. You can add an exception by adding something like `exclude: ^\.github/.*\.md$` to the `markdownlint` hook in `.pre-commit-config.yaml`.

**Review by Holzhaus — APPROVED** [review]
LGTM, waiting for CI.

**Comment by Holzhaus** [comment]
All passed, thank you very much!

**Pull request merged**
